language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.2.1
before_script:
  - dotnet restore
script:  
  - dotnet test ./test/QuartzHostedService.Test -c Release
  - dotnet build -c Release