language: csharp  
mono: none
dotnet: 3.0
sudo: required  
os: linux
dist: xenial  
before_script:
  - dotnet restore
script:  
  - dotnet test ./test/QuartzHostedService.Test -c Release
  - dotnet build -c Release